import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Layout from '@/src/layout/layout'
import axios from 'axios'
import { useEffect, useState } from 'react'
import useSWR from 'swr';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [cep,setCep] = useState(""); 
  const [endereco,setEndereco] = useState(""); 
  const [cidade,setCidade] = useState("");
  const [uf,setUf] = useState("");

  const handleSubmit = async (e) => {
    e.preventDefault();

    setEndereco('');
    setCidade('');
    setUf('');

    let dataCep = await axios.get('https://viacep.com.br/ws/'+cep+'/json/')
                  .then(function (response) {
                    console.log(response.data);
                    return response.data;
                  })
                  .catch(function (error) {
                    console.log(error);
                  });

    setEndereco(dataCep.logradouro);
    setCidade(dataCep.localidade);
    setUf(dataCep.uf);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main className={styles.main}>
          <h1>Primeiro app sergio</h1>
        
          <form onSubmit={handleSubmit}>
            <label for="first">CEP:</label>
            <br/>
            <input 
              type="text" 
              value={cep} 
              onChange={(e) => {setCep(e.target.value)}}
              required
              minlength="8"
              maxlength="8" 
              pattern="[0-9]{1,15}"
            />
            <button type="submit">Pesquisar</button>
            <br/>
            <label for="first">Endereço</label>
            <br/>
            <input 
              type="text" 
              value={endereco}
              onChange={(e) => {setEndereco(e.target.value)}} 
            />
            <br/>
            <label for="first">Cidade</label>
            <br/>
            <input 
              type="text" 
              value={cidade}
              onChange={(e) => {setCidade(e.target.value)}} 
            />
            <br/>
            <label for="first">UF</label>
            <br/>
            <input 
              type="text" 
              value={uf}
              onChange={(e) => {setUf(e.target.value)}} 
            />
          </form>
        </main>
      </Layout>
    </>
  )
}
