import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Layout from '@/src/layout/layout'
import axios from 'axios'
import { useEffect, useState } from 'react'
import useSWR from 'swr';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  //const { data, error, isLoading } = useSWR('http://127.0.0.1:8000/api/auth/todos',  (url) => {
  const { data, error, isLoading } = useSWR('https://jsonplaceholder.typicode.com/todos',  (url) => {
     return axios.get(url)
    .then(function (response) {
      console.log(response.data);
      return response.data;
    })
    .catch(function (error) {
      console.log(error);
    });
  })

  if (isLoading) 
    return <p>Loading ...</p>
  else{
    console.log(data);
  }


 /*const [todos,setTodos] = useState([]); 

  useEffect(() => {
    const iniciar = async () => {
      await axios.get('http://127.0.0.1:8000/api/auth/todos')
      //await axios.get('https://jsonplaceholder.typicode.com/todos')
      .then(function (response) {
        console.log(response);
        setTodos(response.data);
      })
      .catch(function (error) {
        console.log(error);
      });
    }

    iniciar();
  },[])*/

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main className={styles.main}>
          <h1>Primeiro app sergio</h1>
          {data.map((value,index) => {
            return(
              <div key={index}>
                
                <h5>{value.name ? value.name : value.title}</h5>
              </div>
            );
          })}
        </main>
      </Layout>
    </>
  )
}
