import Head from 'next/head'
import { Inter } from 'next/font/google'
import Layout from '@/src/layout/layout'
import axios from 'axios'
import { useEffect, useState } from 'react'
import useSWR from 'swr';

const inter = Inter({ subsets: ['latin'] })

export default function Sobre() {

 const [todos,setTodos] = useState([]); 

  useEffect(() => {
    const iniciar = async () => {
      //await axios.get('http://127.0.0.1:8000/api/auth/todos')
      await axios.get('https://jsonplaceholder.typicode.com/todos')
      .then(function (response) {
        console.log(response);
        //setTodos([...todos, response.data]);
        setTodos(response.data);
      })
      .catch(function (error) {
        console.log(error);
      });
    }

    iniciar();
  },[])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main >
          <h1>Hallo World</h1>
          {todos.map((value,index) => {
            return(
              <div key={index}>
                
                <h5>{value.name ? value.name : value.title}</h5>
              </div>
            );
          })}
        </main>
      </Layout>
    </>
  )
}
